import { useAuth } from "@/_core/hooks/useAuth";
import StorefrontLayout from "@/components/StorefrontLayout";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, Loader2, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const sparklesEmoji = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/kXzBrYNIYeExUoGY.svg";

export default function Account() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const [name, setName] = useState("");
  const saveName = trpc.auth.setMemberDisplayName.useMutation({ onSuccess: () => utils.auth.me.invalidate() });
  const memberName = user?.displayName;
  const save = (skip = false) => saveName.mutate({ name: skip ? undefined : name });

  return <StorefrontLayout><main className="container grid min-h-[calc(100vh-13rem)] place-items-center py-6 sm:py-10"><section className="glass-panel relative w-full max-w-2xl overflow-hidden rounded-[1.5rem] p-5 sm:p-9"><img src={sparklesEmoji} alt="" aria-hidden="true" className="emoji-asset float-emoji absolute right-8 top-7 h-7 w-7" /><div className="relative max-w-lg"><p className="text-[10px] font-bold tracking-[0.16em] text-indigo-700">MY ZURS</p><h1 className="mt-2 font-display text-2xl font-bold leading-tight text-slate-950 sm:text-4xl">គណនីរបស់អ្នក</h1>{loading ? <div className="mt-5 flex items-center gap-2 rounded-xl bg-white/70 p-4 text-xs text-slate-600"><Loader2 className="h-4 w-4 animate-spin text-indigo-600" />កំពុងរៀបចំគណនី…</div> : !user ? <SignedOutCard /> : memberName ? <MemberCard name={memberName} isAdmin={user.role === "admin"} /> : <OnboardingCard name={name} onNameChange={setName} pending={saveName.isPending} error={saveName.error?.message} onSave={() => save(false)} onSkip={() => save(true)} />}</div></section></main></StorefrontLayout>;
}

function SignedOutCard() { return <><p className="mt-3 text-xs leading-6 text-slate-600 sm:text-sm sm:leading-7">ចូលគណនីរបស់អ្នក ដើម្បីរក្សាទុកព័ត៌មាន និងគ្រប់គ្រងសកម្មភាពរបស់អ្នកជាមួយ ZURS STORE។</p><div className="mt-5 rounded-xl border border-white/90 bg-white/65 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><UserRound className="h-5 w-5" /></div><div><p className="text-sm font-bold text-slate-900">ZURS Member</p><p className="mt-0.5 text-xs text-slate-500">ចូលគណនីរបស់អ្នកដើម្បីបន្ត។</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-emerald-800"><ShieldCheck className="h-4 w-4" />ប្រើប្រាស់បានងាយស្រួល និងមានទំនុកចិត្ត</div></div><Link href="/google-sign-in" className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">ចូលគណនី <ArrowRight className="h-4 w-4" /></Link></>; }
function MemberCard({ name, isAdmin }: { name: string; isAdmin: boolean }) { return <><p className="mt-3 text-xs leading-6 text-slate-600 sm:text-sm sm:leading-7">គណនី ZURS Member របស់អ្នករួចរាល់សម្រាប់រក្សាទុកសកម្មភាព និងប្រើប្រាស់សេវាកម្ម។</p><div className="mt-5 rounded-xl border border-white/90 bg-white/65 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><UserRound className="h-5 w-5" /></div><div><p className="text-sm font-bold text-slate-900">{name}</p><p className="mt-0.5 text-xs text-slate-500">ZURS Member</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-emerald-800"><Check className="h-4 w-4" />ឈ្មោះសមាជិកត្រូវបានរក្សាទុក</div></div>{isAdmin && <div className="mt-4 rounded-xl border border-indigo-100 bg-indigo-50/70 p-4"><p className="text-xs font-bold text-slate-900">Gmail Sender របស់ ZURS STORE</p><p className="mt-1 text-[11px] leading-5 text-slate-600">ភ្ជាប់ Gmail របស់ម្ចាស់ ដើម្បីផ្ញើ welcome email ទៅអ្នកប្រើថ្មី។ Google នឹងសុំសិទ្ធិផ្ញើអ៊ីមែលតែសម្រាប់គណនី sender នេះប៉ុណ្ណោះ។</p><a href="/api/auth/google/sender" className="mt-3 inline-flex h-9 items-center rounded-lg bg-slate-950 px-3 text-xs font-bold text-white">ភ្ជាប់ Gmail Sender</a></div>}</>; }
function OnboardingCard({ name, onNameChange, pending, error, onSave, onSkip }: { name: string; onNameChange: (next: string) => void; pending: boolean; error?: string; onSave: () => void; onSkip: () => void }) { return <div className="mt-5 rounded-xl border border-white/90 bg-white/65 p-4 sm:p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><UserRound className="h-5 w-5" /></div><div><p className="text-sm font-bold text-slate-900">បង្កើតឈ្មោះ ZURS Member</p><p className="mt-0.5 text-xs text-slate-500">បញ្ចូលឈ្មោះ ឬរំលងសម្រាប់លេខសមាជិកស្វ័យប្រវត្តិ។</p></div></div><label className="mt-4 block"><span className="mb-1.5 block text-xs font-bold text-slate-700">ឈ្មោះរបស់អ្នក</span><div className="flex overflow-hidden rounded-xl border border-slate-200 bg-white focus-within:border-indigo-400"><input value={name} onChange={(event) => onNameChange(event.target.value)} maxLength={120} placeholder="ឧ. Makara" className="h-10 min-w-0 flex-1 px-3 text-sm outline-none" /><span className="flex items-center border-l border-slate-200 bg-slate-50 px-3 text-[10px] font-bold text-indigo-700">ZURS Member</span></div></label><p className="mt-2 text-[11px] leading-5 text-slate-500">ឈ្មោះទាំងអស់នឹងបញ្ចប់ដោយ <strong>ZURS Member</strong>។ ប្រសិនបើអ្នករំលង យើងនឹងបង្កើតលេខសមាជិកឱ្យអ្នក។</p>{error ? <p className="mt-2 text-xs text-rose-600">{error}</p> : null}<div className="mt-4 grid gap-2 sm:grid-cols-2"><button disabled={pending} onClick={onSave} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-bold text-white disabled:opacity-60">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}រក្សាទុកឈ្មោះ</button><button disabled={pending} onClick={onSkip} className="h-10 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700 disabled:opacity-60">រំលង និងបង្កើតលេខ</button></div></div>; }
