import StorefrontLayout from "@/components/StorefrontLayout";
import { PaymentMethods } from "@/components/PaymentMethods";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, CreditCard, Loader2, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function Checkout() {
  const [location] = useLocation();
  const orderId = location.split("/").pop() ?? "";
  const session = trpc.orders.paymentSession.useQuery({ orderId }, { enabled: orderId.length >= 4 });

  return <StorefrontLayout><main className="container max-w-xl pt-7 sm:pt-12"><Link href="/account" className="inline-flex items-center gap-1 text-xs font-bold text-indigo-700"><ArrowLeft className="h-3.5 w-3.5" />ត្រឡប់ទៅគណនីរបស់ខ្ញុំ</Link>{session.isLoading ? <div className="mt-6 grid h-64 place-items-center rounded-2xl border border-slate-200 bg-white"><Loader2 className="h-6 w-6 animate-spin text-indigo-600" /></div> : session.error || !session.data ? <div className="glass-panel mt-6 rounded-2xl p-6 text-center"><CreditCard className="mx-auto h-7 w-7 text-indigo-600" /><p className="mt-3 text-sm font-bold text-slate-900">មិនអាចបើកព័ត៌មានការកម្មង់នេះបានទេ</p><p className="mt-1 text-xs leading-5 text-slate-500">សូមត្រឡប់ទៅគណនីរបស់អ្នក ហើយព្យាយាមម្តងទៀត។</p><Link href="/account" className="mt-5 inline-flex h-10 items-center rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">ទៅកាន់គណនី</Link></div> : <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl shadow-slate-200/40"><div className="bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-indigo-200"><CreditCard className="h-4 w-4" /><span className="text-xs font-bold tracking-[0.12em]">PAYMENT</span></div><h1 className="mt-3 font-display text-2xl font-bold">{session.data.order.productName}</h1><p className="mt-1 text-xs text-slate-400">{session.data.order.orderNumber}</p><p className="mt-5 font-display text-3xl font-bold">${Number(session.data.order.subtotal).toFixed(2)}</p></div><div className="p-5"><div className="flex items-start gap-3 rounded-xl bg-indigo-50 p-4 text-xs leading-6 text-indigo-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-indigo-700" /><p><strong>សូមពិនិត្យព័ត៌មានការកម្មង់របស់អ្នក។</strong> ព័ត៌មានលម្អិត និងស្ថានភាពនឹងត្រូវបានរក្សាទុកក្នុងគណនីរបស់អ្នក។</p></div><div className="mt-5 flex items-center gap-2 text-xs text-emerald-800"><CheckCircle2 className="h-4 w-4" />ព័ត៌មានការកម្មង់ត្រូវបានរៀបចំរួចរាល់</div><PaymentMethods /><Link href="/account" className="mt-5 flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 text-xs font-bold text-white">មើលព័ត៌មានការកម្មង់</Link></div></section>}</main></StorefrontLayout>;
}
