import StorefrontLayout from "@/components/StorefrontLayout";
import { formatUsd } from "@/lib/display";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, ChevronLeft, ChevronRight, Filter, Handshake, Image as ImageIcon, Loader2, Megaphone, Plus, Search, Send, ShieldCheck, Tag, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const tabs = [{ id: "all", label: "ទាំងអស់" }, { id: "sale", label: "លក់គណនី" }, { id: "swap", label: "ដូរគណនី" }, { id: "wanted", label: "ទិញ/ស្វែងរក" }] as const;
const gameFilters = ["ទាំងអស់", "Mobile Legends", "Free Fire", "PUBG Mobile", "Blox Fruits"];
type GalleryState = { images: string[]; index: number; title: string };

export default function Marketplace() {
  const [tab, setTab] = useState<"all" | "sale" | "swap" | "wanted">("all");
  const [game, setGame] = useState("ទាំងអស់");
  const [query, setQuery] = useState("");
  const [contactListingId, setContactListingId] = useState<string | null>(null);
  const [contactMessage, setContactMessage] = useState("");
  const [gallery, setGallery] = useState<GalleryState | null>(null);
  const { isAuthenticated } = useAuth();
  const listings = trpc.marketplace.list.useQuery({ listingType: tab === "all" ? undefined : tab, game: game === "ទាំងអស់" ? undefined : game, search: query || undefined });
  const contact = trpc.marketplace.contact.useMutation({ onSuccess: () => { setContactListingId(null); setContactMessage(""); } });
  const selectedListing = listings.data?.find((item) => item.id === contactListingId);
  const handleContact = () => { if (!isAuthenticated) { window.location.assign("/google-sign-in"); return; } if (contactListingId && contactMessage.trim()) contact.mutate({ listingId: contactListingId, message: contactMessage }); };

  return <StorefrontLayout><main className="container pt-7 sm:pt-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.14em] text-fuchsia-700">ACCOUNT MARKETPLACE</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight text-slate-950">ទីផ្សារគណនីហ្គេម</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">ស្វែងរកគណនីសម្រាប់ទិញ, ប្រកាសលក់ ឬចាប់ផ្តើមការដូរគណនីរបស់អ្នក។ ការផ្សាយថ្មីត្រូវការការពិនិត្យជាមុន។</p></div><Link href="/marketplace/sell" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white transition-transform hover:-translate-y-0.5 active:scale-[0.97]"><Plus className="h-4 w-4" />ដាក់លក់គណនី</Link></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><ModeCard icon={Tag} title="លក់គណនី" copy="បញ្ចូលព័ត៌មាន រូបភាព និងតម្លៃ។" /><ModeCard icon={Megaphone} title="ទិញ/ស្វែងរក" copy="ប្រកាសអំពីគណនីដែលអ្នកកំពុងស្វែងរក។" /><ModeCard icon={Handshake} title="ដូរគណនី" copy="ស្វែងរកអ្នកលេងដែលចង់ដូរគណនី។" /></section>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={cn("whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold transition-colors", tab === item.id ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500 hover:text-slate-800")}>{item.label}</button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ស្វែងរកការផ្សាយ" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none focus:border-indigo-500 sm:w-52" /></div><label className="relative"><Filter className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><select value={game} onChange={(event) => setGame(event.target.value)} className="h-10 w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-8 text-xs font-semibold text-slate-700 outline-none focus:border-indigo-500 sm:w-44">{gameFilters.map((item) => <option key={item}>{item}</option>)}</select></label></div></div></section>
    {listings.isLoading ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-56 animate-pulse rounded-2xl bg-slate-200" />)}</div> : <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{listings.data?.map((listing) => <MarketplaceCard key={listing.id} listing={listing} onContact={() => setContactListingId(listing.id)} onGallery={(images, index) => setGallery({ images, index, title: listing.title })} />)}</section>}
    {!listings.isLoading && !listings.data?.length && <div className="glass-panel relative mt-5 overflow-hidden rounded-2xl p-10 text-center"><span className="float-emoji absolute right-[15%] top-5 text-xl">🔎</span><span className="float-emoji float-emoji--slow absolute bottom-5 left-[14%] text-lg">✨</span><Search className="relative mx-auto h-6 w-6 text-indigo-300" /><p className="relative mt-3 text-sm font-bold text-slate-700">មិនទាន់មានការផ្សាយស្របនឹងលក្ខខណ្ឌនេះទេ</p><p className="relative mt-1 text-xs text-slate-500">ការផ្សាយដែលអនុម័តនឹងបង្ហាញនៅទីនេះ។</p></div>}
    <div className="glass-panel mt-7 flex items-start gap-3 rounded-2xl p-4 text-xs leading-6 text-emerald-900"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" /><p><strong>ការពារទីផ្សារ៖</strong> ការផ្សាយលក់ និងការដូរគណនីថ្មី ត្រូវឆ្លងកាត់ការពិនិត្យពីអ្នកគ្រប់គ្រង មុននឹងបង្ហាញជាសាធារណៈ។</p></div>
    {contactListingId && <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[0.12em] text-indigo-700">CONTACT REQUEST</p><h2 className="mt-1 font-display text-lg font-bold text-slate-950">{selectedListing?.title ?? "ការផ្សាយ"}</h2></div><button onClick={() => setContactListingId(null)} className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-600" aria-label="Close contact request"><X className="h-4 w-4" /></button></div>{selectedListing?.telegramUsername && <a href={`https://t.me/${selectedListing.telegramUsername.replace(/^@/, "")}`} target="_blank" rel="noreferrer" className="mt-4 flex h-10 items-center justify-center gap-2 rounded-xl bg-sky-50 text-xs font-bold text-sky-700">Telegram: @{selectedListing.telegramUsername.replace(/^@/, "")}</a>}<textarea value={contactMessage} onChange={(event) => setContactMessage(event.target.value)} rows={4} placeholder="សរសេរសាររបស់អ្នកទៅកាន់ម្ចាស់ការផ្សាយ..." className="mt-4 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-indigo-500 focus:bg-white" /><button disabled={!contactMessage.trim() || contact.isPending} onClick={handleContact} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-bold text-white disabled:opacity-40">{contact.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{isAuthenticated ? "ផ្ញើសំណើ" : "ចូលគណនី ដើម្បីផ្ញើ"}</button>{contact.error && <p className="mt-2 text-xs text-rose-600">{contact.error.message}</p>}</div></div>}
    {gallery && <GalleryModal gallery={gallery} onClose={() => setGallery(null)} onMove={(direction) => setGallery((current) => current ? { ...current, index: (current.index + direction + current.images.length) % current.images.length } : null)} onSelect={(index) => setGallery((current) => current ? { ...current, index } : null)} />}
  </main></StorefrontLayout>;
}

function MarketplaceCard({ listing, onContact, onGallery }: { listing: { id: string; listingType: "sale" | "swap" | "wanted"; createdAt: Date; game: string; title: string; rankLevel: string; description: string; priceUsd: string | null; telegramUsername: string | null; screenshots: unknown }; onContact: () => void; onGallery: (images: string[], index: number) => void }) {
  const screenshots = Array.isArray(listing.screenshots) ? listing.screenshots.filter((item): item is string => typeof item === "string" && /^https?:\/\//.test(item)) : [];
  return <article className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-lg"><div className={cn("flex items-center justify-between px-4 py-3", listing.listingType === "sale" ? "bg-indigo-50" : listing.listingType === "swap" ? "bg-fuchsia-50" : "bg-amber-50")}><span className={cn("rounded-full px-2 py-1 text-[10px] font-bold", listing.listingType === "sale" ? "bg-indigo-100 text-indigo-700" : listing.listingType === "swap" ? "bg-fuchsia-100 text-fuchsia-700" : "bg-amber-100 text-amber-700")}>{listing.listingType === "sale" ? "លក់គណនី" : listing.listingType === "swap" ? "ដូរគណនី" : "ស្វែងរកទិញ"}</span><span className="text-[10px] font-medium text-slate-500">{new Date(listing.createdAt).toLocaleDateString("km-KH")}</span></div><div className="p-4"><p className="text-[11px] font-bold text-indigo-700">{listing.game}</p><h2 className="mt-1 font-display text-base font-bold text-slate-900">{listing.title}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{listing.rankLevel}</p><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-600">{listing.description}</p>{screenshots.length > 0 && <div className="mt-3 grid grid-cols-4 gap-1.5">{screenshots.slice(0, 4).map((image, index) => <button type="button" key={image} onClick={() => onGallery(screenshots, index)} className="relative aspect-square overflow-hidden rounded-lg bg-slate-100 ring-offset-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><img src={image} alt={`${listing.title} screenshot ${index + 1}`} className="h-full w-full object-cover" loading="lazy" />{index === 3 && screenshots.length > 4 && <span className="absolute inset-0 grid place-items-center bg-slate-950/55 text-xs font-bold text-white">+{screenshots.length - 4}</span>}</button>)}</div>}<div className="mt-4 flex items-center justify-between gap-3">{listing.priceUsd ? <span className="font-display text-lg font-bold text-slate-950">{formatUsd(listing.priceUsd)}</span> : <span className="text-xs font-semibold text-slate-500">សួរបន្ថែម</span>}<button onClick={onContact} className="inline-flex shrink-0 items-center gap-1 text-xs font-bold text-indigo-700">ទំនាក់ទំនង <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" /></button></div>{listing.telegramUsername && <a href={`https://t.me/${listing.telegramUsername.replace(/^@/, "")}`} target="_blank" rel="noreferrer" className="mt-3 flex h-9 items-center justify-center gap-2 rounded-lg bg-sky-50 text-xs font-bold text-sky-700">Telegram: @{listing.telegramUsername.replace(/^@/, "")}</a>}{screenshots.length > 0 && <button type="button" onClick={() => onGallery(screenshots, 0)} className="mt-2 inline-flex items-center gap-1 text-[11px] font-bold text-slate-500 hover:text-indigo-700"><ImageIcon className="h-3.5 w-3.5" />មើលរូបភាព {screenshots.length} រូប</button>}</div></article>;
}

function GalleryModal({ gallery, onClose, onMove, onSelect }: { gallery: GalleryState; onClose: () => void; onMove: (direction: -1 | 1) => void; onSelect: (index: number) => void }) { return <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/85 p-3 sm:p-6" role="dialog" aria-modal="true" aria-label={`Image gallery for ${gallery.title}`}><div className="w-full max-w-4xl rounded-2xl bg-white p-3 shadow-2xl sm:p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-display text-sm font-bold text-slate-900">{gallery.title}</p><p className="mt-1 text-[11px] text-slate-500">រូបភាព {gallery.index + 1} / {gallery.images.length}</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600" aria-label="Close image gallery"><X className="h-4 w-4" /></button></div><div className="relative mt-3 flex h-[56vh] min-h-72 items-center justify-center overflow-hidden rounded-xl bg-slate-950"><img src={gallery.images[gallery.index]} alt={`${gallery.title} screenshot ${gallery.index + 1}`} className="h-full w-full object-contain" /><button onClick={() => onMove(-1)} className="absolute left-2 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-slate-900 shadow-sm" aria-label="Previous image"><ChevronLeft className="h-5 w-5" /></button><button onClick={() => onMove(1)} className="absolute right-2 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-slate-900 shadow-sm" aria-label="Next image"><ChevronRight className="h-5 w-5" /></button></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{gallery.images.map((image, index) => <button type="button" key={image} onClick={() => onSelect(index)} className={cn("h-14 w-14 shrink-0 overflow-hidden rounded-lg border-2", index === gallery.index ? "border-indigo-500" : "border-transparent")}><img src={image} alt={`Choose screenshot ${index + 1}`} className="h-full w-full object-cover" /></button>)}</div></div></div>; }
function ModeCard({ icon: Icon, title, copy }: { icon: typeof Tag; title: string; copy: string }) { return <div className="glass-panel group relative flex items-start gap-3 overflow-hidden rounded-2xl p-4"><span className="float-emoji absolute right-3 top-2 text-sm opacity-0 transition-opacity group-hover:opacity-100">✨</span><div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-700 shadow-sm"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-bold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{copy}</p></div></div>; }
