import StorefrontLayout from "@/components/StorefrontLayout";
import { startLogin } from "@/const";
import { formatUsd } from "@/lib/display";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, Filter, Handshake, Loader2, Megaphone, Plus, Search, Send, ShieldCheck, Tag, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const tabs = [{ id: "all", label: "ទាំងអស់" }, { id: "sale", label: "លក់គណនី" }, { id: "swap", label: "ដូរគណនី" }, { id: "wanted", label: "ទិញ/ស្វែងរក" }] as const;
const gameFilters = ["ទាំងអស់", "Mobile Legends", "Free Fire", "PUBG Mobile", "Blox Fruits"];
export default function Marketplace() {
  const [tab, setTab] = useState<"all" | "sale" | "swap" | "wanted">("all"); const [game, setGame] = useState("ទាំងអស់"); const [query, setQuery] = useState(""); const [contactListingId, setContactListingId] = useState<string | null>(null); const [contactMessage, setContactMessage] = useState(""); const { isAuthenticated } = useAuth();
  const listings = trpc.marketplace.list.useQuery({ listingType: tab === "all" ? undefined : tab, game: game === "ទាំងអស់" ? undefined : game, search: query || undefined }); const contact = trpc.marketplace.contact.useMutation({ onSuccess: () => { setContactListingId(null); setContactMessage(""); } }); const selectedListing = listings.data?.find((item) => item.id === contactListingId);
  const handleContact = () => { if (!isAuthenticated) { startLogin(); return; } if (contactListingId && contactMessage.trim()) contact.mutate({ listingId: contactListingId, message: contactMessage }); };
  return <StorefrontLayout><main className="container pt-7 sm:pt-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.14em] text-fuchsia-700">ACCOUNT MARKETPLACE</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight text-slate-950">ទីផ្សារគណនីហ្គេម</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">ស្វែងរកគណនីសម្រាប់ទិញ, ប្រកាសលក់ ឬចាប់ផ្តើមការដូរគណនីរបស់អ្នក។ ការផ្សាយថ្មីត្រូវការការពិនិត្យជាមុន។</p></div><Link href="/marketplace/sell" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white transition-transform hover:-translate-y-0.5 active:scale-[0.97]"><Plus className="h-4 w-4" />ដាក់លក់គណនី</Link></div>
  <section className="mt-7 grid gap-3 sm:grid-cols-3"><ModeCard icon={Tag} title="លក់គណនី" copy="បញ្ចូលព័ត៌មាន រូបភាព និងតម្លៃ។" /><ModeCard icon={Megaphone} title="ទិញ/ស្វែងរក" copy="ប្រកាសអំពីគណនីដែលអ្នកកំពុងស្វែងរក។" /><ModeCard icon={Handshake} title="ដូរគណនី" copy="ស្វែងរកអ្នកលេងដែលចង់ដូរគណនី។" /></section>
  <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={cn("whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold transition-colors", tab === item.id ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500 hover:text-slate-800")}>{item.label}</button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ស្វែងរកការផ្សាយ" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none focus:border-indigo-500 sm:w-52" /></div><label className="relative"><Filter className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><select value={game} onChange={(event) => setGame(event.target.value)} className="h-10 w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-8 text-xs font-semibold text-slate-700 outline-none focus:border-indigo-500 sm:w-44">{gameFilters.map((item) => <option key={item}>{item}</option>)}</select></label></div></div></section>
  {listings.isLoading ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-56 animate-pulse rounded-2xl bg-slate-200" />)}</div> : <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{listings.data?.map((listing) => <article key={listing.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-lg"><div className={cn("flex items-center justify-between px-4 py-3", listing.listingType === "sale" ? "bg-indigo-50" : listing.listingType === "swap" ? "bg-fuchsia-50" : "bg-amber-50")}><span className={cn("rounded-full px-2 py-1 text-[10px] font-bold", listing.listingType === "sale" ? "bg-indigo-100 text-indigo-700" : listing.listingType === "swap" ? "bg-fuchsia-100 text-fuchsia-700" : "bg-amber-100 text-amber-700")}>{listing.listingType === "sale" ? "លក់គណនី" : listing.listingType === "swap" ? "ដូរគណនី" : "ស្វែងរកទិញ"}</span><span className="text-[10px] font-medium text-slate-500">{new Date(listing.createdAt).toLocaleDateString("km-KH")}</span></div><div className="p-4"><p className="text-[11px] font-bold text-indigo-700">{listing.game}</p><h2 className="mt-1 font-display text-base font-bold text-slate-900">{listing.title}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{listing.rankLevel}</p><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-600">{listing.description}</p><div className="mt-4 flex items-center justify-between">{listing.priceUsd ? <span className="font-display text-lg font-bold text-slate-950">{formatUsd(listing.priceUsd)}</span> : <span className="text-xs font-semibold text-slate-500">សួរបន្ថែម</span>}<button onClick={() => setContactListingId(listing.id)} className="inline-flex items-center gap-1 text-xs font-bold text-indigo-700">ទំនាក់ទំនង <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" /></button></div></div></article>)}</section>}
  {!listings.isLoading && !listings.data?.length && <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Search className="mx-auto h-6 w-6 text-slate-300" /><p className="mt-3 text-sm font-bold text-slate-700">មិនទាន់មានការផ្សាយស្របនឹងលក្ខខណ្ឌនេះទេ</p><p className="mt-1 text-xs text-slate-500">ការផ្សាយដែលអនុម័តនឹងបង្ហាញនៅទីនេះ។</p></div>}
  <div className="mt-7 flex items-start gap-3 rounded-2xl bg-emerald-50 p-4 text-xs leading-6 text-emerald-900"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" /><p><strong>ការពារទីផ្សារ៖</strong> ការផ្សាយលក់ និងការដូរគណនីថ្មី ត្រូវឆ្លងកាត់ការពិនិត្យពីអ្នកគ្រប់គ្រង មុននឹងបង្ហាញជាសាធារណៈ។</p></div>
  {contactListingId && <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[0.12em] text-indigo-700">CONTACT REQUEST</p><h2 className="mt-1 font-display text-lg font-bold text-slate-950">{selectedListing?.title ?? "ការផ្សាយ"}</h2></div><button onClick={() => setContactListingId(null)} className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-600" aria-label="Close contact request"><X className="h-4 w-4" /></button></div><textarea value={contactMessage} onChange={(event) => setContactMessage(event.target.value)} rows={4} placeholder="សរសេរសាររបស់អ្នកទៅកាន់ម្ចាស់ការផ្សាយ..." className="mt-4 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-indigo-500 focus:bg-white" /><button disabled={!contactMessage.trim() || contact.isPending} onClick={handleContact} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-bold text-white disabled:opacity-40">{contact.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{isAuthenticated ? "ផ្ញើសំណើ" : "ចូលគណនី ដើម្បីផ្ញើ"}</button>{contact.error && <p className="mt-2 text-xs text-rose-600">{contact.error.message}</p>}</div></div>}
  </main></StorefrontLayout>; }
function ModeCard({ icon: Icon, title, copy }: { icon: typeof Tag; title: string; copy: string }) { return <div className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-700"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-bold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{copy}</p></div></div>; }
