import { useAuth } from "@/_core/hooks/useAuth";
import StorefrontLayout from "@/components/StorefrontLayout";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3, Loader2, PackageCheck } from "lucide-react";
import { Link } from "wouter";

export default function MyMarketplaceListings() {
  const { isAuthenticated } = useAuth(); const listings = trpc.marketplace.mine.useQuery(undefined, { enabled: isAuthenticated }); const utils = trpc.useUtils(); const markSold = trpc.marketplace.markSold.useMutation({ onSuccess: () => utils.marketplace.mine.invalidate() });
  if (!isAuthenticated) return <StorefrontLayout><main className="container max-w-xl py-10"><section className="glass-panel rounded-2xl p-6 text-center"><h1 className="font-display text-2xl font-bold text-slate-950">ការផ្សាយរបស់ខ្ញុំ</h1><p className="mt-2 text-sm text-slate-600">សូមចូលគណនីដើម្បីគ្រប់គ្រងការផ្សាយ។</p><Link href="/google-sign-in" className="mt-5 inline-flex h-10 items-center rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">ចូលគណនី</Link></section></main></StorefrontLayout>;
  return <StorefrontLayout><main className="container max-w-3xl py-7 sm:py-10"><Link href="/marketplace" className="text-xs font-bold text-indigo-700">← ត្រឡប់ទៅទីផ្សារ</Link><h1 className="mt-3 font-display text-3xl font-bold text-slate-950">ការផ្សាយរបស់ខ្ញុំ</h1><p className="mt-2 text-sm leading-6 text-slate-600">ពេលគណនីបានលក់រួច សូមកំណត់ជា Sold out។ Listing នឹងបាត់ពីសាធារណៈភ្លាមៗ ហើយលុបចោលក្រោយ 5 ម៉ោង។</p><section className="mt-6 space-y-3">{listings.isLoading ? <div className="grid h-32 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-indigo-600" /></div> : !listings.data?.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-xs text-slate-500">អ្នកមិនទាន់មានការផ្សាយទេ។</div> : listings.data.map((listing) => <article key={listing.id} className="surface flex flex-col gap-3 rounded-2xl p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold text-slate-900">{listing.title}</p><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{listing.status}</span></div><p className="mt-1 text-xs text-slate-500">{listing.game} · {listing.rankLevel}</p>{listing.status === "sold" && listing.cleanupAt ? <p className="mt-2 flex items-center gap-1 text-[11px] text-amber-800"><Clock3 className="h-3.5 w-3.5" />លុបចោលនៅ {new Date(listing.cleanupAt).toLocaleString()}</p> : null}</div>{["approved", "pending"].includes(listing.status) ? <button disabled={markSold.isPending} onClick={() => markSold.mutate({ listingId: listing.id })} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-bold text-white disabled:opacity-50"><PackageCheck className="h-4 w-4" />Sold out</button> : <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" />{listing.status === "sold" ? "បានកំណត់ Sold out" : "បានបិទ"}</span>}</article>)}</section></main></StorefrontLayout>;
}
