import StorefrontLayout from "@/components/StorefrontLayout";
import { formatUsd } from "@/lib/display";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { CheckCircle2, CircleDollarSign, ExternalLink, Instagram, Loader2, Send, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const liveSmmCatalogConnected = false;

export default function Smm() {
  const [, setLocation] = useLocation(); const catalog = trpc.catalog.smm.useQuery(); const { isAuthenticated } = useAuth(); const [serviceId, setServiceId] = useState(""); const [tierId, setTierId] = useState(""); const [target, setTarget] = useState(""); const [createdOrder, setCreatedOrder] = useState<{ orderNumber: string; amount: string } | null>(null);
  useEffect(() => { if (!catalog.data?.length) return; const current = catalog.data.find((item) => item.id === serviceId) ?? catalog.data[0]; if (current.id !== serviceId) { setServiceId(current.id); setTierId(current.tiers[0]?.id ?? ""); } }, [catalog.data, serviceId]);
  const service = catalog.data?.find((item) => item.id === serviceId) ?? catalog.data?.[0]; const tier = useMemo(() => service?.tiers.find((item) => item.id === tierId) ?? service?.tiers[0], [service, tierId]); const platformCount = useMemo(() => new Set(catalog.data?.map((item) => item.platform) ?? []).size, [catalog.data]);
  const startPayment = trpc.orders.beginPayment.useMutation({ onSuccess: (result) => setLocation(result.payment.checkoutUrl ?? `/checkout/${result.order.id}`) });
  const createOrder = trpc.orders.createSmm.useMutation({ onSuccess: (result) => { setCreatedOrder({ orderNumber: result.orderNumber, amount: result.amount }); startPayment.mutate({ orderId: result.id }); } });
  const selectService = (id: string) => { const next = catalog.data?.find((item) => item.id === id); if (!next) return; setServiceId(next.id); setTierId(next.tiers[0]?.id ?? ""); setCreatedOrder(null); };
  const checkout = () => { if (!isAuthenticated) { setLocation("/google-sign-in"); return; } if (tier && target.trim()) createOrder.mutate({ tierId: tier.id, target }); };
  if (!liveSmmCatalogConnected) return <StorefrontLayout><main className="container grid min-h-[calc(100vh-13rem)] place-items-center py-6 sm:py-10"><section className="premium-shine relative w-full max-w-2xl overflow-hidden rounded-[1.5rem] bg-gradient-to-br from-[#241043] via-[#301866] to-[#56279a] p-5 text-white shadow-2xl shadow-violet-900/20 sm:p-9"><div className="glass-orb float-emoji right-8 top-7 grid h-11 w-11 place-items-center rounded-xl text-xl">📈</div><div className="float-emoji float-emoji--slow absolute bottom-7 right-24 text-2xl">✨</div><div className="relative max-w-lg"><p className="text-[10px] font-bold tracking-[0.16em] text-fuchsia-200">LIVE SOCIAL CATALOG</p><h1 className="mt-2 font-display text-2xl font-bold leading-tight sm:text-4xl">សេវា SMM ពិតកំពុងត្រៀម</h1><p className="mt-3 text-xs leading-6 text-violet-100/90 sm:text-sm sm:leading-7">មិនមាន Followers, Likes ឬ Views សាកល្បងនៅទីនេះទេ។ សេវាបន្តផ្ទាល់នឹងលេចឡើងក្រោយពេលភ្ជាប់ API អ្នកផ្គត់ផ្គង់ដែលបានអនុញ្ញាត។</p><div className="mt-5 rounded-xl border border-white/10 bg-white/8 p-3"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300" /><p className="text-xs font-bold">ការពារទិន្នន័យ និងតម្លៃពិត</p></div><p className="mt-2 text-[10px] leading-5 text-violet-100/70">អ្នកគ្រប់គ្រងនឹងពិនិត្យកាតាឡុកមុនពេលបើកការទិញ។</p></div><button disabled className="mt-5 flex h-10 w-full cursor-not-allowed items-center justify-center gap-2 rounded-xl bg-white/80 text-xs font-bold text-slate-500"><CircleDollarSign className="h-4 w-4" />សេវាបន្តផ្ទាល់កំពុងរង់ចាំ</button></div></section></main></StorefrontLayout>;
  return <StorefrontLayout><main className="container pt-4 sm:pt-10"><div className="premium-shine relative overflow-hidden rounded-[1.2rem] bg-gradient-to-br from-[#261149] via-[#392076] to-[#5a2aa0] px-4 py-5 text-white sm:rounded-[1.5rem] sm:px-8 sm:py-9"><div className="glass-orb float-emoji right-7 top-5 grid h-8 w-8 place-items-center rounded-lg text-sm">📈</div><div className="flex items-center gap-2 text-fuchsia-200"><Sparkles className="h-3.5 w-3.5" /><span className="text-[10px] font-bold tracking-[0.14em]">SOCIAL BOOST</span></div><h1 className="mt-2 max-w-xl font-display text-2xl font-bold leading-tight tracking-tight sm:mt-3 sm:text-4xl">កញ្ចប់ SMM សម្រាប់ការរីកចម្រើនរបស់អ្នក</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-violet-100/85 sm:mt-3 sm:text-sm sm:leading-7">ជ្រើសសេវា និងបរិមាណដែលត្រូវការ។ តម្លៃសរុបត្រូវបានបង្ហាញភ្លាមៗ មុនពេលអ្នកបន្តការកម្មង់។</p><div className="mt-3 inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/10 px-2.5 py-1.5 text-[10px] text-violet-100 sm:mt-5 sm:px-3 sm:py-2 sm:text-xs"><Instagram className="h-3.5 w-3.5" />គាំទ្រ {platformCount || "…"}+ Platforms</div></div>
    {catalog.isLoading ? <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="h-64 animate-pulse rounded-xl bg-slate-200" /><div className="h-52 animate-pulse rounded-xl bg-slate-900" /></div> : !service ? <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-600">បច្ចុប្បន្នមិនទាន់មានសេវា SMM សម្រាប់បង្ហាញទេ។</div> : <div className="mt-4 grid gap-3 lg:mt-6 lg:grid-cols-[1fr_0.9fr] lg:gap-5"><section className="surface rounded-xl p-3 sm:rounded-2xl sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-[13px] font-bold text-slate-900 sm:text-sm">ជ្រើសរើសសេវា</h2><p className="mt-1 text-[10px] text-slate-500 sm:text-xs">Followers, likes, views និងសេវាផ្សេងៗ។</p></div><span className="rounded-full bg-fuchsia-50 px-2 py-1 text-[9px] font-bold text-fuchsia-700">តម្លៃច្បាស់</span></div><div className="mt-3 grid gap-1.5 sm:mt-5 sm:grid-cols-2 sm:gap-2">{catalog.data?.map((item) => <button key={item.id} onClick={() => selectService(item.id)} className={cn("flex items-center gap-2 rounded-lg border p-2 text-left transition-all sm:gap-3 sm:rounded-xl sm:p-3", item.id === serviceId ? "border-fuchsia-400 bg-fuchsia-50" : "border-slate-200 bg-white hover:border-fuchsia-200 hover:bg-slate-50")}><div className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-fuchsia-500 to-violet-600 text-[9px] font-bold text-white sm:h-10 sm:w-10 sm:rounded-xl sm:text-[10px]">{item.iconLabel}</div><div className="min-w-0"><p className="font-display text-[13px] font-bold text-slate-900 sm:text-sm">{item.platform}</p><p className="mt-0.5 truncate text-[10px] text-slate-500 sm:text-xs">{item.titleKh}</p></div></button>)}</div></section>
      <aside className="row-span-2 h-fit rounded-xl bg-slate-950 p-3 text-white shadow-xl shadow-violet-900/15 sm:rounded-2xl sm:p-5 lg:sticky lg:top-24"><p className="text-[10px] font-bold tracking-[0.13em] text-fuchsia-300 sm:text-xs">ORDER SUMMARY</p><h2 className="mt-2 font-display text-lg font-bold sm:mt-3 sm:text-xl">{service.platform} — {service.titleKh}</h2><p className="mt-1 text-[10px] leading-4 text-slate-400 sm:text-xs sm:leading-5">{service.descriptionKh}</p><div className="my-3 h-px bg-white/10 sm:my-5" /><p className="text-[10px] font-semibold text-slate-300 sm:text-xs">Target Link / Username</p><div className="relative mt-1.5 sm:mt-2"><ExternalLink className="absolute left-3 top-3 h-3.5 w-3.5 text-slate-500 sm:top-3.5 sm:h-4 sm:w-4" /><input value={target} onChange={(event) => setTarget(event.target.value)} placeholder="https://... or @username" className="h-10 w-full rounded-xl border border-white/10 bg-white/8 pl-9 pr-3 text-xs text-white outline-none placeholder:text-slate-500 focus:border-fuchsia-300 focus:ring-2 focus:ring-fuchsia-400/20 sm:h-11 sm:pl-10 sm:text-sm" /></div><div className="mt-3 flex items-center justify-between sm:mt-5"><span className="text-xs text-slate-300 sm:text-sm">សរុប</span><span className="font-display text-xl font-bold sm:text-2xl">{tier ? formatUsd(tier.priceUsd) : "—"}</span></div><button disabled={!target.trim() || createOrder.isPending || startPayment.isPending} onClick={checkout} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-white text-xs font-bold text-slate-950 transition-transform hover:bg-fuchsia-50 disabled:cursor-not-allowed disabled:opacity-40 active:scale-[0.97] sm:mt-5 sm:h-11 sm:text-sm">{createOrder.isPending || startPayment.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <CircleDollarSign className="h-4 w-4" />}{isAuthenticated ? "បន្តទៅការទូទាត់" : "ចូលដោយ Google ដើម្បីបន្ត"}</button>{(createOrder.error || startPayment.error) && <p className="mt-2 rounded-lg bg-rose-500/15 p-2 text-[10px] leading-4 text-rose-100 sm:mt-3 sm:p-2.5 sm:text-xs sm:leading-5">{createOrder.error?.message ?? startPayment.error?.message}</p>}{createdOrder && <div className="mt-3 rounded-xl bg-emerald-500/15 p-2 text-[10px] leading-5 text-emerald-100 sm:mt-4 sm:p-3 sm:text-xs sm:leading-6"><CheckCircle2 className="mr-1.5 inline h-4 w-4" />ការកម្មង់ <strong>{createdOrder.orderNumber}</strong> ត្រូវបានបង្កើត។</div>}</aside>
      <section className="surface rounded-xl p-3 sm:rounded-2xl sm:p-5"><h2 className="text-[13px] font-bold text-slate-900 sm:text-sm">ជ្រើសរើសបរិមាណ</h2><div className="mt-3 grid gap-1.5 sm:mt-4 sm:grid-cols-3 sm:gap-2">{service.tiers.map((rate) => <button key={rate.id} onClick={() => { setTierId(rate.id); setCreatedOrder(null); }} className={cn("rounded-lg border p-2 text-left transition-all sm:rounded-xl sm:p-3", tierId === rate.id ? "border-fuchsia-400 bg-fuchsia-50" : "border-slate-200 hover:border-fuchsia-200")}><p className="font-display text-base font-bold text-slate-900 sm:text-lg">{rate.quantity.toLocaleString()}</p><p className="mt-0.5 text-[10px] text-slate-500 sm:text-[11px]">{service.titleKh}</p><p className="mt-1.5 text-[11px] font-bold text-fuchsia-700 sm:mt-2 sm:text-xs">{formatUsd(rate.priceUsd)}</p></button>)}</div><p className="mt-3 flex items-start gap-2 rounded-xl bg-slate-50 p-2.5 text-[10px] leading-5 text-slate-600 sm:mt-5 sm:p-3 sm:text-xs sm:leading-6"><Send className="mt-0.5 h-3.5 w-3.5 shrink-0 text-violet-600 sm:h-4 sm:w-4" />ដំណើរការបញ្ជាទិញនឹងចាប់ផ្តើម បន្ទាប់ពីការទូទាត់បានជោគជ័យ។</p></section></div>}</main></StorefrontLayout>;
}
