import StorefrontLayout from "@/components/StorefrontLayout";
import { ArrowRight, Heart, ShieldCheck, TrendingUp } from "lucide-react";
import { Link } from "wouter";

const sparklesEmoji = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/kXzBrYNIYeExUoGY.svg";

export default function Smm() {
  return <StorefrontLayout><main className="container grid min-h-[calc(100vh-13rem)] place-items-center py-6 sm:py-10"><section className="premium-shine relative w-full max-w-3xl overflow-hidden rounded-[1.5rem] bg-gradient-to-br from-[#241043] via-[#301866] to-[#56279a] p-5 text-white shadow-2xl shadow-violet-900/20 sm:p-9"><div className="absolute -left-14 bottom-0 h-52 w-52 rounded-full bg-fuchsia-500/30 blur-3xl" /><img src={sparklesEmoji} alt="" aria-hidden="true" className="emoji-asset float-emoji absolute right-8 top-7 h-9 w-9" /><div className="relative max-w-xl"><p className="text-[10px] font-bold tracking-[0.16em] text-fuchsia-200">ZURS SOCIAL BOOST</p><h1 className="mt-2 font-display text-2xl font-bold leading-tight sm:text-4xl">ជួយឱ្យ Social របស់អ្នកកាន់តែសកម្ម</h1><p className="mt-3 text-xs leading-6 text-violet-100/90 sm:text-sm sm:leading-7">ស្វែងរកបទពិសោធន៍ SMM ដែលមានរចនាបថស្អាត ទាន់សម័យ និងងាយស្រួលប្រើនៅលើទូរស័ព្ទ។</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/8 p-3"><TrendingUp className="h-4 w-4 text-fuchsia-200" /><p className="mt-2 text-xs font-bold">Social Momentum</p><p className="mt-1 text-[10px] leading-5 text-violet-100/70">រៀបចំសម្រាប់ Instagram, TikTok និង Platform ផ្សេងៗ។</p></div><div className="rounded-xl border border-white/10 bg-white/8 p-3"><ShieldCheck className="h-4 w-4 text-emerald-300" /><p className="mt-2 text-xs font-bold">ផ្តោតលើទំនុកចិត្ត</p><p className="mt-1 text-[10px] leading-5 text-violet-100/70">ព័ត៌មានទាំងអស់ត្រូវបានបង្ហាញឱ្យងាយស្រួលយល់។</p></div></div><Link href="/" className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl bg-white px-4 text-xs font-bold text-violet-950">ត្រឡប់ទៅទំព័រដើម <ArrowRight className="h-4 w-4" /></Link></div></section></main></StorefrontLayout>;
}
