import StorefrontLayout from "@/components/StorefrontLayout";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, CircleDollarSign, Gamepad2, Loader2, RefreshCw, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";
import { useMemo, useState } from "react";

const brandAssets = {
  gamepad: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/RDtUjAOwCGqQQWNR.svg",
  diamond: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/DwbIkeuSyFFKbYEk.svg",
};

export default function Topup() {
  const gamesQuery = trpc.provider.games.useQuery();
  const [gameId, setGameId] = useState("");
  const [details, setDetails] = useState<Record<string, string>>({});
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [selectedOfferId, setSelectedOfferId] = useState<string | null>(null);
  const providerPackages = trpc.provider.packages.useMutation();
  const games = gamesQuery.data?.games ?? [];
  const selectedGame = useMemo(() => games.find((game) => game.id === gameId) ?? null, [games, gameId]);
  const offers = providerPackages.data?.packages ?? [];
  const selectedOffer = useMemo(() => offers.find((offer) => offer.id === selectedOfferId) ?? null, [offers, selectedOfferId]);
  const fieldsReady = Boolean(selectedGame && selectedGame.requiredFields.filter((field) => field.required).every((field) => details[field.key]?.trim()));
  const changeGame = (nextGameId: string) => { setGameId(nextGameId); setDetails({}); setSelectedOfferId(null); providerPackages.reset(); };
  const requestPackages = () => { if (!selectedGame || !fieldsReady) return; setSelectedOfferId(null); setDrawerOpen(true); providerPackages.mutate({ gameId: selectedGame.id, fields: details }); };

  return <StorefrontLayout><main className="container py-5 sm:py-10">
    <section className="relative mx-auto max-w-5xl overflow-hidden rounded-[1.5rem] bg-slate-950 p-5 text-white shadow-2xl shadow-indigo-900/20 sm:p-8"><div className="absolute -right-16 -top-20 h-60 w-60 rounded-full bg-indigo-500/35 blur-3xl" /><img src={brandAssets.gamepad} alt="" aria-hidden="true" className="emoji-asset absolute right-8 top-7 h-9 w-9" /><div className="relative grid gap-6 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><p className="text-[10px] font-bold tracking-[0.16em] text-indigo-200">ZURS GAME TOP-UP</p><h1 className="mt-2 font-display text-3xl font-bold leading-tight sm:text-4xl">ជ្រើសរើសហ្គេមរបស់អ្នក</h1><p className="mt-3 text-sm leading-7 text-slate-300">បន្ទាប់ពីជ្រើសហ្គេម ទម្រង់ព័ត៌មាន និងកញ្ចប់ដែលត្រូវការនឹងបង្ហាញតាមសេវាកម្មនោះ។</p><div className="mt-5 flex items-center gap-2 text-xs text-emerald-200"><ShieldCheck className="h-4 w-4" />បង្ហាញតែព័ត៌មានដែលសេវាកម្មជ្រើសរើសត្រូវការ</div></div><section className="rounded-2xl border border-white/10 bg-white/7 p-4 backdrop-blur sm:p-5"><div className="flex items-center justify-between"><p className="text-sm font-bold">ជំហានទី១៖ ជ្រើសហ្គេម</p><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold text-indigo-100">1 / 2</span></div><label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold text-slate-200">ហ្គេម</span><select value={gameId} onChange={(event) => changeGame(event.target.value)} disabled={gamesQuery.isLoading || !games.length} className="h-11 w-full rounded-xl border border-white/15 bg-slate-900/70 px-3 text-sm text-white outline-none disabled:opacity-50"><option value="">{gamesQuery.isLoading ? "កំពុងស្វែងរកហ្គេម…" : "ជ្រើសរើសហ្គេម"}</option>{games.map((game) => <option key={game.id} value={game.id}>{game.name}</option>)}</select></label>{selectedGame ? <form onSubmit={(event) => { event.preventDefault(); requestPackages(); }} className="mt-4"><div className="grid gap-3 sm:grid-cols-2">{selectedGame.requiredFields.map((field) => <DynamicField key={field.key} field={field} value={details[field.key] ?? ""} onChange={(value) => setDetails((current) => ({ ...current, [field.key]: value }))} />)}</div><button type="submit" disabled={!fieldsReady || providerPackages.isPending} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-slate-950 transition-transform hover:-translate-y-0.5 active:scale-[0.97] disabled:cursor-not-allowed disabled:opacity-45">{providerPackages.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}បន្តជ្រើសកញ្ចប់ <ChevronRight className="h-4 w-4" /></button></form> : <div className="mt-4 rounded-xl border border-white/10 bg-slate-900/55 p-4 text-xs leading-5 text-slate-300">សូមជ្រើសហ្គេម ដើម្បីបន្ត។</div>}</section></div></section>
    <section className="mx-auto mt-5 grid max-w-5xl gap-3 sm:grid-cols-3"><InfoTile icon={Gamepad2} title="ជ្រើសហ្គេម" copy="សេវាកម្មនីមួយៗមានតម្រូវការផ្ទាល់ខ្លួន។" /><InfoTile icon={Sparkles} title="បំពេញព័ត៌មាន" copy="បង្ហាញតែទម្រង់ដែលត្រូវការសម្រាប់ហ្គេមជ្រើសរើស។" /><InfoTile icon={WalletCards} title="បង់ប្រាក់" copy="ពិនិត្យកញ្ចប់ និងការទូទាត់មុនបន្ត។" /></section>
    {drawerOpen && <div className="fixed inset-0 z-60 flex items-end bg-slate-950/45 p-2 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5" role="dialog" aria-modal="true" aria-label="Package and payment summary"><section className="liquid-checkout w-full max-w-4xl overflow-hidden rounded-[1.5rem] p-4 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.16em] text-indigo-700">PACKAGE &amp; PAYMENT</p><h2 className="mt-1 font-display text-xl font-bold text-slate-950 sm:text-2xl">ជ្រើសរើសកញ្ចប់របស់អ្នក</h2></div><button onClick={() => setDrawerOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-600" aria-label="Close package selection"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div><PackageResponse state={providerPackages.data?.status} pending={providerPackages.isPending} error={providerPackages.error?.message} offers={offers} selectedOfferId={selectedOfferId} onSelect={setSelectedOfferId} onRetry={requestPackages} /></div><aside className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center gap-2 text-indigo-200"><CircleDollarSign className="h-4 w-4" /><span className="text-xs font-bold tracking-[0.12em]">PAYMENT SUMMARY</span></div><div className="mt-4 space-y-3 text-xs"><SummaryRow label="Game" value={selectedGame?.name ?? "—"} />{selectedGame?.requiredFields.map((field) => <SummaryRow key={field.key} label={field.label} value={details[field.key] || "—"} />)}<SummaryRow label="Package" value={selectedOffer?.label ?? "—"} /><SummaryRow label="Amount" value={selectedOffer?.amountLabel ?? "—"} /><div className="h-px bg-white/10" /><SummaryRow label="Price" value={selectedOffer?.priceLabel ?? "—"} bold /></div><button disabled={!selectedOffer} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-45">{selectedOffer ? <Check className="h-4 w-4" /> : <Loader2 className="h-4 w-4" />}បង់ប្រាក់ <ChevronRight className="h-4 w-4" /></button></aside></div></section></div>}
  </main></StorefrontLayout>;
}

function DynamicField({ field, value, onChange }: { field: { key: string; label: string; placeholder?: string; required: boolean; kind: "text" | "number" }; value: string; onChange: (next: string) => void }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-200">{field.label}{field.required ? <span className="ml-1 text-indigo-200">*</span> : null}</span><input required={field.required} type={field.kind} value={value} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder ?? field.label} className="h-11 w-full rounded-xl border border-white/15 bg-slate-900/70 px-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-indigo-300" /></label>; }
function PackageResponse({ state, pending, error, offers, selectedOfferId, onSelect, onRetry }: { state?: "ready" | "unavailable" | "error"; pending: boolean; error?: string; offers: { id: string; label: string; amountLabel: string; priceLabel: string; provider: string; paymentMethods: ("khqr" | "bank")[] }[]; selectedOfferId: string | null; onSelect: (id: string) => void; onRetry: () => void }) { if (pending) return <div className="grid min-h-52 place-items-center rounded-2xl border border-dashed border-slate-200 bg-white/70 text-center"><div><Loader2 className="mx-auto h-7 w-7 animate-spin text-indigo-600" /><p className="mt-3 text-sm font-bold text-slate-800">កំពុងស្វែងរកកញ្ចប់</p><p className="mt-1 text-xs text-slate-500">សូមរង់ចាំបន្តិច…</p></div></div>; if (error || state === "error") return <ResponseMessage title="មិនអាចបង្ហាញកញ្ចប់បានទេ" copy="សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។" action="ព្យាយាមម្តងទៀត" onAction={onRetry} />; if (state === "unavailable") return <ResponseMessage title="កញ្ចប់មិនទាន់មានសម្រាប់ពេលនេះ" copy="សូមត្រឡប់មកពិនិត្យម្តងទៀតនៅពេលក្រោយ។" />; if (!offers.length) return <ResponseMessage title="មិនមានកញ្ចប់សមស្របទេ" copy="សូមពិនិត្យព័ត៌មានដែលបានបញ្ចូល ឬជ្រើសហ្គេមផ្សេង។" />; return <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{offers.map((offer) => <button key={offer.id} onClick={() => onSelect(offer.id)} className={`rounded-xl border p-3 text-left transition ${selectedOfferId === offer.id ? "border-indigo-500 bg-indigo-50" : "border-slate-200 bg-white hover:border-indigo-200"}`}><p className="text-sm font-bold text-slate-900">{offer.label}</p><p className="mt-1 text-xs text-slate-500">{offer.amountLabel}</p><p className="mt-3 text-sm font-extrabold text-indigo-700">{offer.priceLabel}</p></button>)}</div>; }
function ResponseMessage({ title, copy, action, onAction }: { title: string; copy: string; action?: string; onAction?: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-white/70 p-7 text-center"><img src={brandAssets.diamond} alt="" aria-hidden="true" className="emoji-asset mx-auto h-9 w-9" /><p className="mt-3 text-sm font-bold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p>{action && onAction ? <button onClick={onAction} className="mt-4 inline-flex h-9 items-center gap-1.5 rounded-xl bg-slate-950 px-3 text-xs font-bold text-white"><RefreshCw className="h-3.5 w-3.5" />{action}</button> : null}</div>; }
function InfoTile({ icon: Icon, title, copy }: { icon: typeof Gamepad2; title: string; copy: string }) { return <div className="glass-panel flex gap-3 rounded-2xl p-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-bold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div></div>; }
function SummaryRow({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="text-slate-400">{label}</span><span className={`max-w-[65%] truncate text-right ${bold ? "font-display text-base font-bold text-white" : "font-semibold text-white"}`}>{value}</span></div>; }
