import StorefrontLayout from "@/components/StorefrontLayout";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, CircleDollarSign, Gamepad2, Loader2, RefreshCw, ShieldCheck, WalletCards, X } from "lucide-react";
import { useMemo, useState } from "react";

const brandAssets = { gamepad: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/RDtUjAOwCGqQQWNR.svg", diamond: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663688034315/DwbIkeuSyFFKbYEk.svg" };

export default function Topup() {
  const gamesQuery = trpc.provider.games.useQuery();
  const [gameId, setGameId] = useState("");
  const [details, setDetails] = useState<Record<string, string>>({});
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [selectedOfferId, setSelectedOfferId] = useState<string | null>(null);
  const providerPackages = trpc.provider.packages.useMutation();
  const games = gamesQuery.data?.games ?? [];
  const selectedGame = useMemo(() => games.find((game) => game.id === gameId) ?? null, [games, gameId]);
  const offers = providerPackages.data?.packages ?? [];
  const selectedOffer = useMemo(() => offers.find((offer) => offer.id === selectedOfferId) ?? null, [offers, selectedOfferId]);
  const fieldsReady = Boolean(selectedGame && selectedGame.requiredFields.filter((field) => field.required).every((field) => details[field.key]?.trim()));
  const changeGame = (nextGameId: string) => { setGameId(nextGameId); setDetails({}); setSelectedOfferId(null); providerPackages.reset(); };
  const requestPackages = () => { if (!selectedGame || !fieldsReady) return; setSelectedOfferId(null); setDrawerOpen(true); providerPackages.mutate({ gameId: selectedGame.id, fields: details }); };

  return <StorefrontLayout><main className="container py-5 sm:py-10">
    <section className="relative mx-auto max-w-5xl overflow-hidden rounded-[1.5rem] bg-slate-950 p-5 text-white shadow-xl shadow-indigo-900/15 sm:p-8"><div className="absolute -right-16 -top-20 h-60 w-60 rounded-full bg-indigo-500/24 blur-3xl" /><img src={brandAssets.gamepad} alt="" aria-hidden="true" className="emoji-asset absolute right-7 top-6 h-8 w-8" /><div className="relative max-w-3xl"><p className="text-[10px] font-bold tracking-[0.16em] text-indigo-200">ZURS GAME TOP-UP</p><h1 className="mt-2 font-display text-3xl font-bold leading-tight sm:text-4xl">ទិញពេជ្យ និង Top-up ហ្គេម</h1><p className="mt-3 text-sm leading-7 text-slate-300">ជ្រើសហ្គេមដែលអ្នកចង់បញ្ចូលពេជ្យខាងក្រោម។ អ្នកនឹងឃើញ Logo, ឈ្មោះហ្គេម និងទម្រង់ Player ID/Zone ID ត្រឹមត្រូវសម្រាប់ហ្គេមនោះ។</p></div></section>
    <section className="surface mx-auto mt-4 max-w-5xl rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-base font-bold text-slate-950">ជំហានទី 1៖ ជ្រើសហ្គេមរបស់អ្នក</p><p className="mt-1 text-xs leading-5 text-slate-500">Logo និងឈ្មោះហ្គេមត្រូវបានទទួលពី provider ដែលបានអនុញ្ញាត។ ជ្រើសហ្គេមមុន ទើបយើងអាចស្គាល់ព័ត៌មានដែលត្រូវការសម្រាប់ top-up។</p></div><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold text-indigo-700">1 / 3</span></div>
      {gamesQuery.isLoading ? <div className="mt-4 grid min-h-36 place-items-center rounded-xl bg-slate-50 text-xs text-slate-500"><Loader2 className="mb-2 h-5 w-5 animate-spin text-indigo-600" />កំពុងស្វែងរកបញ្ជីហ្គេម…</div> : games.length ? <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{games.map((game) => <button key={game.id} type="button" onClick={() => changeGame(game.id)} className={`group rounded-2xl border p-3 text-left transition ${gameId === game.id ? "border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100" : "border-slate-200 bg-white hover:border-indigo-300"}`}><div className="flex items-center gap-3">{game.logoUrl ? <img src={game.logoUrl} alt={`${game.name} logo`} className="h-11 w-11 rounded-xl object-cover" /> : <div className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-600"><Gamepad2 className="h-5 w-5" /></div>}<div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{game.name}</p><p className="mt-0.5 truncate text-[10px] text-slate-500">{game.provider}</p></div></div></button>)}</div> : <div className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-xs leading-6 text-slate-600">បញ្ជីហ្គេមមិនទាន់មាននៅពេលនេះទេ។ ពេល provider ផ្លូវការរបស់ហាងភ្ជាប់រួច Logo, ឈ្មោះហ្គេម និងកញ្ចប់ពេជ្យពិតប្រាកដនឹងបង្ហាញនៅទីនេះ។</div>}
      {selectedGame && <form onSubmit={(event) => { event.preventDefault(); requestPackages(); }} className="mt-6 border-t border-slate-100 pt-5"><div className="flex items-center justify-between gap-3"><div><p className="text-base font-bold text-slate-950">ជំហានទី 2៖ បញ្ចូលព័ត៌មាន {selectedGame.name}</p><p className="mt-1 text-xs text-slate-500">សូមបំពេញព័ត៌មានដែល provider ត្រូវការដើម្បីរកកញ្ចប់ពេជ្យ។</p></div><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold text-indigo-700">2 / 3</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{selectedGame.requiredFields.map((field) => <DynamicField key={field.key} field={field} value={details[field.key] ?? ""} onChange={(value) => setDetails((current) => ({ ...current, [field.key]: value }))} />)}</div><button type="submit" disabled={!fieldsReady || providerPackages.isPending} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-bold text-white disabled:opacity-45">{providerPackages.isPending && <Loader2 className="h-4 w-4 animate-spin" />}មើលកញ្ចប់ពេជ្យ និងតម្លៃ <ChevronRight className="h-4 w-4" /></button></form>}</section>
    <section className="mx-auto mt-4 grid max-w-5xl gap-3 sm:grid-cols-3"><Step icon={<Gamepad2 className="h-4 w-4" />} title="ជ្រើស Logo និងឈ្មោះហ្គេម" copy="មើលកាតហ្គេមខាងលើ ហើយចុចហ្គេមដែលអ្នកចង់ទិញពេជ្យ។" /><Step icon={<WalletCards className="h-4 w-4" />} title="បញ្ចូល Player ID / Zone ID" copy="ទម្រង់នឹងផ្លាស់ប្តូរតាមហ្គេមដែលបានជ្រើស ដើម្បីកុំឲ្យបញ្ចូលព័ត៌មានខុស។" /><Step icon={<CircleDollarSign className="h-4 w-4" />} title="ជ្រើសកញ្ចប់ និងបង់ប្រាក់" copy="ពិនិត្យចំនួនពេជ្យ តម្លៃ និងព័ត៌មានគណនីម្តងទៀត មុនបន្តបង់ប្រាក់។" /></section>
    {drawerOpen && <div className="fixed inset-0 z-60 flex items-end bg-slate-950/45 p-2 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5" role="dialog" aria-modal="true" aria-label="Package and payment summary"><section className="liquid-checkout w-full max-w-4xl overflow-hidden rounded-[1.5rem] p-4 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.16em] text-indigo-700">PACKAGE &amp; PAYMENT</p><h2 className="mt-1 font-display text-xl font-bold text-slate-950 sm:text-2xl">ជ្រើសរើសកញ្ចប់ពេជ្យរបស់អ្នក</h2></div><button onClick={() => setDrawerOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-600" aria-label="Close package selection"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div><PackageResponse state={providerPackages.data?.status} pending={providerPackages.isPending} error={providerPackages.error?.message} offers={offers} selectedOfferId={selectedOfferId} onSelect={setSelectedOfferId} onRetry={requestPackages} /></div><aside className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center gap-2 text-indigo-200"><CircleDollarSign className="h-4 w-4" /><span className="text-xs font-bold tracking-[0.12em]">PAYMENT SUMMARY</span></div><div className="mt-4 space-y-3 text-xs"><SummaryRow label="Game" value={selectedGame?.name ?? "—"} />{selectedGame?.requiredFields.map((field) => <SummaryRow key={field.key} label={field.label} value={details[field.key] || "—"} />)}<SummaryRow label="Package" value={selectedOffer?.label ?? "—"} /><SummaryRow label="Diamonds / Amount" value={selectedOffer?.amountLabel ?? "—"} /><div className="h-px bg-white/10" /><SummaryRow label="Price" value={selectedOffer?.priceLabel ?? "—"} bold /></div><button disabled={!selectedOffer} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-slate-950 disabled:opacity-45">{selectedOffer ? <Check className="h-4 w-4" /> : <Loader2 className="h-4 w-4" />}បង់ប្រាក់ <ChevronRight className="h-4 w-4" /></button></aside></div></section></div>}
  </main></StorefrontLayout>;
}
function DynamicField({ field, value, onChange }: { field: { key: string; label: string; placeholder?: string; required: boolean; kind: "text" | "number" }; value: string; onChange: (next: string) => void }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{field.label}{field.required && <span className="ml-1 text-indigo-600">*</span>}</span><input required={field.required} type={field.kind} value={value} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder ?? field.label} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 outline-none placeholder:text-slate-400 focus:border-indigo-500 focus:bg-white" /></label>; }
function Step({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="surface rounded-2xl p-4"><div className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-50 text-indigo-700">{icon}</div><p className="mt-3 text-sm font-bold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div>; }
function PackageResponse({ state, pending, error, offers, selectedOfferId, onSelect, onRetry }: { state?: "ready" | "unavailable" | "error"; pending: boolean; error?: string; offers: { id: string; label: string; amountLabel: string; priceLabel: string; provider: string; paymentMethods: ("khqr" | "bank")[] }[]; selectedOfferId: string | null; onSelect: (id: string) => void; onRetry: () => void }) { if (pending) return <div className="grid min-h-52 place-items-center rounded-2xl border border-dashed border-slate-200 bg-white/70 text-center"><div><Loader2 className="mx-auto h-7 w-7 animate-spin text-indigo-600" /><p className="mt-3 text-sm font-bold text-slate-800">កំពុងស្វែងរកកញ្ចប់ពេជ្យ</p></div></div>; if (error || state === "error") return <ResponseMessage title="មិនអាចបង្ហាញកញ្ចប់បានទេ" copy="សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។" action="ព្យាយាមម្តងទៀត" onAction={onRetry} />; if (state === "unavailable") return <ResponseMessage title="កញ្ចប់មិនទាន់មានសម្រាប់ពេលនេះ" copy="សូមត្រឡប់មកពិនិត្យម្តងទៀតនៅពេលក្រោយ។" />; if (!offers.length) return <ResponseMessage title="មិនមានកញ្ចប់សមស្របទេ" copy="សូមពិនិត្យព័ត៌មានដែលបានបញ្ចូល ឬជ្រើសហ្គេមផ្សេង។" />; return <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{offers.map((offer) => <button type="button" key={offer.id} onClick={() => onSelect(offer.id)} className={`rounded-xl border p-3 text-left ${selectedOfferId === offer.id ? "border-indigo-500 bg-indigo-50" : "border-slate-200 bg-white"}`}><p className="text-sm font-bold text-slate-900">{offer.label}</p><p className="mt-1 text-xs text-slate-500">{offer.amountLabel}</p><p className="mt-3 text-sm font-extrabold text-indigo-700">{offer.priceLabel}</p></button>)}</div>; }
function ResponseMessage({ title, copy, action, onAction }: { title: string; copy: string; action?: string; onAction?: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-white/70 p-7 text-center"><img src={brandAssets.diamond} alt="" aria-hidden="true" className="emoji-asset mx-auto h-9 w-9" /><p className="mt-3 text-sm font-bold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p>{action && onAction && <button type="button" onClick={onAction} className="mt-4 inline-flex h-9 items-center gap-1.5 rounded-xl bg-slate-950 px-3 text-xs font-bold text-white"><RefreshCw className="h-3.5 w-3.5" />{action}</button>}</div>; }
function SummaryRow({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="text-slate-400">{label}</span><span className={`max-w-[65%] truncate text-right ${bold ? "font-display text-base font-bold text-white" : "font-semibold text-white"}`}>{value}</span></div>; }
