import {createHash,createCipheriv,createDecipheriv,randomBytes} from "node:crypto";
import type {DeliveryType,ServiceDelivery,ServiceState} from "../shared/partnerService";
export const serviceIntentHash=(v:{productSlug:string;quantity:number;customerNote:string})=>createHash("sha256").update(JSON.stringify([v.productSlug,v.quantity,v.customerNote.trim()])).digest("hex");
function key(){const v=process.env.SERVICE_DELIVERY_ENCRYPTION_KEY?.trim();if(!v||!/^[A-Za-z0-9+/]{43}=$/.test(v))throw new Error("Delivery encryption is not configured.");const k=Buffer.from(v,"base64");if(k.length!==32)throw new Error("Invalid delivery key.");return k;}
export function assertDeliveryReady(){key();}
export function validateServiceDelivery(type:DeliveryType,quantity:number,v:ServiceDelivery):ServiceDelivery{if(v.type!==type||!Array.isArray(v.items)||v.items.length!==quantity)throw new Error("Provide one delivery item per purchased unit, matching the delivery type.");const items=v.items.map(s=>{if(typeof s!=="string"||!s.trim()||s.length>8000)throw new Error("Invalid delivery item.");if(type==="LINK"){const u=new URL(s.trim());if(u.protocol!=="https:"||u.username||u.password)throw new Error("Links must use HTTPS without embedded credentials.");}return s.trim();});if(typeof v.instructions!=="string"||v.instructions.length>4000||Buffer.byteLength(JSON.stringify(items),"utf8")>32000)throw new Error("Delivery too long.");return {type,items,instructions:v.instructions.trim()};}
export function encryptServiceDelivery(id:string,v:ServiceDelivery){const plain=JSON.stringify(v);if(Buffer.byteLength(plain,"utf8")>45000)throw new Error("Delivery too long.");const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv);c.setAAD(Buffer.from(`zurs-service:${id}`));const data=Buffer.concat([c.update(plain,"utf8"),c.final()]);return JSON.stringify({v:1,iv:iv.toString("base64"),tag:c.getAuthTag().toString("base64"),data:data.toString("base64")});}
export function decryptServiceDelivery(id:string,value:string):ServiceDelivery{try{const e=JSON.parse(value);if(e.v!==1)throw new Error();const c=createDecipheriv("aes-256-gcm",key(),Buffer.from(e.iv,"base64"));c.setAAD(Buffer.from(`zurs-service:${id}`));c.setAuthTag(Buffer.from(e.tag,"base64"));return JSON.parse(Buffer.concat([c.update(Buffer.from(e.data,"base64")),c.final()]).toString("utf8"));}catch{throw new Error("Delivery could not be opened. Contact the owner; do not replace the encryption key.");}}
export function assertDeliveryOwner(v:{userId:number;orderUserId:number;requestUserId:number;orderStatus:string;requestStatus:string;hasDelivery:boolean}){if(v.userId!==v.orderUserId||v.userId!==v.requestUserId)throw new Error("NOT_FOUND");if(v.orderStatus!=="delivered"||v.requestStatus!=="delivered"||!v.hasDelivery)throw new Error("NOT_READY");}
export type ServiceAction="start"|"complete"|"needs_attention"|"refund";
export function nextServiceState(v:{orderStatus:string;status:ServiceState;assignedAdminId:number|null;actorUserId:number;action:ServiceAction;refundConfirmed?:boolean;refundReference?:string}):ServiceState{if(v.action==="complete"&&v.status==="delivered"&&v.orderStatus==="delivered")return "delivered";if(v.action==="refund"&&v.status==="refunded"&&v.orderStatus==="refunded")return "refunded";if(v.orderStatus!=="paid"&&!(v.action==="refund"&&v.orderStatus==="delivered"))throw new Error("Only verified paid orders can be fulfilled.");if(v.status==="refunded"||(v.status==="delivered"&&v.action!=="refund"))throw new Error("This request is closed.");if(v.action!=="refund"&&v.assignedAdminId!==null&&v.assignedAdminId!==v.actorUserId)throw new Error("Another administrator has claimed this order.");if(v.action==="complete"&&(v.status!=="processing"||v.assignedAdminId!==v.actorUserId))throw new Error("Claim the order before completing it.");if(v.action==="refund"&&(!v.refundConfirmed||!v.refundReference?.trim()))throw new Error("Refund the customer externally before recording the transfer reference.");return ({start:"processing",complete:"delivered",needs_attention:"needs_attention",refund:"refunded"} as const)[v.action];}
